name: Bug report
description: Report a bug and help improve the plugin
title: "[BUG] Short description of the bug"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## Description

        A clear and concise description of the bug. Include any relevant details.

        ## Steps to Reproduce

        Provide a step-by-step description:

        1. Go to '...'
        2. Click on '...'
        3. Notice that '...'

        ## Expected Behavior

        What did you expect to happen?

        ## Actual Behavior

        What actually happened? Include error messages if available.

        ## Environment Information

        - **Plugin Version**: [e.g., 1.0.0]
        - **Obsidian Version**: [e.g., v1.3.2]
        - **Operating System**: [e.g., Windows 10]
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I attached a video showing the issue
          required: true
        - label: I attached a sample vault where the issue can be reproduced
          required: true
        - label: I have tested the issue with the latest version
          required: true
        - label: I have checked for existing issues
          required: true
