name: Bug report
title: "[BUG] Short description"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: A clear and concise description of the bug.
  - type: checkboxes
    label: Confirmations
    attributes:
      options:
        - label: "I attached the video showing the issue."
          required: true
        - label: "I attached a sample vault where the issue can be reproduced."
          required: true
