name: Bug report
about: Bug report
title: "[BUG] Short description"
labels: bug
assignees: mnaoumov
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
