name: Bug report
description: Bug report
title: "[BUG] Short description"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: "A clear and concise description of the bug."
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Whenever I visit the user account page (1-2 times a week)"
    validations:
      required: true
