name: Bug report
description: Bug report
title: "[BUG] Short description"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: "A clear and concise description of the bug."
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: Orange cat (required. Everyone likes orange cats.)
          required: true
        - label: "**Black cat**"
