name: Bug report
description: Bug report
title: "[BUG] Short description"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## A clear and concise description of the bug

        TODO

        ## Steps to reproduce

        1. TODO
        2. TODO
        3. TODO
  - type: checkboxes
    attributes:
      label: Confirmations
      description: You have to provide all the required information in order for the plugin developer to be able to work on your bug
      options:
        - label: I attached the video showing the issue
          required: true
        - label: I attached a sample vault where the issue can be reproduced
          required: true
