name: Bug report
title: "[BUG] Short description"
labels: bug
assignees: mnaoumov
body:
  - type: checkboxes
    id: test3
    label: test2
    attributes:
      options:
        - label: "I attached the video showing the issue."
          required: true
        - label: "I attached a sample vault where the issue can be reproduced."
          required: true
