name: Feature request
description: Request a feature and help improve the plugin
title: "[FR] Short description of the feature"
labels: enhancement
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the feature request. Include any relevant details.
    validations:
      required: true
